### PR TITLE
Fix empty wrapper layout

### PR DESCRIPTION
**Pull request by RTimothyEdwards**
Fix empty wrapper layout openframe_project_wrapper_empty.mag.  This file was out of date and does not correspond to the DEF used by openlane (which is correct).  Since the usual openlane flow uses the DEF to generate the top level, then this does not affect any users running the openlane flow.  However, for any user starting with this repository and attempting a manual assembly of the top level starting from the empty wrapper layout, the existing outdated one would cause problems.

### CODE REVIEW

**Comment by marwaneltoukhy** [comment]
@RTimothyEdwards This PR will change the design to the timer design and removes the pico. Is this intentional?

**Comment by RTimothyEdwards** [comment]
@marwaneltoukhy :  No, definitely not intentional.  All I did was to change one file.  Let me try that again.

**Comment by RTimothyEdwards** [comment]
@marwaneltoukhy :  I think I understand what happened.  I intended to make a pull request on `openframe_timer_example`.  I think because it is forked from `openframe_project_example`, it defaulted to merging into that, although I'm not sure why it would do that.  Both projects presumably have the outdated wrapper layout.

**Comment by RTimothyEdwards** [comment]
@marwaneltoukhy :  Okay, that's exactly what happened.  I have regenerated the original patch to openframe_timer_example and I will close this one.

**Pull request closed without merging**
